version: '3.8'
services:
    # Our own app.
    java-maven-app:
      image: ${IMAGE}
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      # Required env variable.
      environment:
        - POSTGRES_PASSWORD=my-pwd
